name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 05:30 UTC
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Allows write access

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{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}}  # Use PAT instead of default token

      - name: Identify user (23f3001462@ds.study.iitm.ac.in)
        run: echo "Running workflow as part of daily commit process"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_update.txt
          git commit -m "Automated daily commit - $(date)"
          git pull --rebase origin main  # Avoid conflicts
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/tarunye/week4.git main  # Use PAT for authentication
